cache: false
# Call environment variables set on Travis CI:
env:
  - URL=https://developer.salesforce.com/media/salesforce-cli/sfdx-linux-amd64.tar.xz
script:
- echo $TRAVIS_EVENT_TYPE
- echo $TRAVIS_PULL_REQUEST
- echo $TRAVIS_PULL_REQUEST_BRANCH

# run commit, PR, PR Merge

install:
# Install sfdx plugins and configure build with sfdx settings
- export SFDX_AUTOUPDATE_DISABLE=false
- export SFDX_USE_GENERIC_UNIX_KEYCHAIN=true
- export SFDX_DOMAIN_RETRY=300
- export SFDX_DISABLE_APP_HUB=true
- export SFDX_LOG_LEVEL=DEBUG
- mkdir sfdx
- wget -qO- $URL | tar xJ -C sfdx --strip-components 1
- "./sfdx/install"
- export PATH=./sfdx/$(pwd):$PATH
- sfdx --version
- sfdx plugins --core

- export BRANCH=$TRAVIS_BRANCH

- >
  if [ "$BRANCH" == "dev" ]; then
    echo $SFDXAUTHURLDEV>authtravisci.txt;
    export TESTLEVEL=RunLocalTests;
  fi;
- >
  if [ "$BRANCH" == "qa" ]; then
    echo $SFDXAUTHURLQA>authtravisci.txt;
    export TESTLEVEL=RunLocalTests;
  fi; 
- >
  if [ "$BRANCH" == "uat" ]; then
    echo $SFDXAUTHURLUAT>authtravisci.txt;
    export TESTLEVEL=RunLocalTests;
  fi; 
- >
  if [ "$BRANCH" == "master" ]; then
    echo $SFDXAUTHURL>authtravisci.txt;
    export TESTLEVEL=RunLocalTests;
  fi; 
- sfdx force:auth:sfdxurl:store -f authtravisci.txt -a targetEnvironment

- export DEPLOYDIR=/Users/jackbarsotti/sfdx-travisci2/force-app/main/default

# Run apex tests and deploy apex classes/triggers
script:
- sfdx force:org:display -u targetEnvironment
- sfdx force:source:deploy -w 10 -p $DEPLOYDIR -l $TESTLEVEL -u targetEnvironment