sudo: true
os: trusty
cache: false
env:
- URL=https://developer.salesforce.com/media/salesforce-cli/sfdx-linux-amd64.tar.xz
before_install:
  #create 3 more line 8's
- if: branch = DEV 
      echo "DEV branch"; 
  fi 
- if: branch = QA 
      echo "QA branch"; 
  fi 
- if: branch = UAT 
      echo "UAT branch"; 
  fi 
- if: branch = master 
      echo "master branch"; 
  fi 
- openssl version
- export SFDX_AUTOUPDATE_DISABLE=false
- export SFDX_USE_GENERIC_UNIX_KEYCHAIN=true
- export SFDX_DOMAIN_RETRY=300
- export SFDX_DISABLE_APP_HUB=true
- export SFDX_LOG_LEVEL=DEBUG
- mkdir sfdx
- wget -qO- $URL | tar xJ -C sfdx --strip-components 1
- "./sfdx/install"
- export PATH=./sfdx/$(pwd):$PATH
- sfdx --version
- sfdx plugins --core
#make 4 more line 21 variables, then use an if statement to distinguish
- echo $SFDXAUTHURL>authtravisci.txt
- sfdx force:auth:sfdxurl:store -f authtravisci.txt -a targetEnvironment
before_script:
- export DEPLOYDIR=force-app/main/default
- export TESTLEVEL=RunLocalTests
- sfdx --version
- sfdx plugins --core
script:
- echo openssl version
- sfdx force:org:display -u targetEnvironment
- sfdx force:source:deploy --wait 10 --sourcepath $DEPLOYDIR --testlevel $TESTLEVEL -u targetEnvironment
- sfdx force:apex:test:run -u targetEnvironment --wait 10
deploy:
  - provider: script
    script: deploymaster.sh
    on:
      branch: master
  - provider: script
    script: deployuat.sh
    on:
      branch: UAT
  - provider: script
    script: deployqa.sh
    on:
      branch: QA
  - provider: script
    script: deploydev.sh
    on:
      branch: DEV
  