cache: false
# Call environment variables set on Travis CI:
env:
  - URL=https://developer.salesforce.com/media/salesforce-cli/sfdx-linux-amd64.tar.xz
notifications:
    webhooks: https://travis-for-jira-prod.toolsplus.app/travis/notifications?token=b217de27-5ba1-367e-92cc-495d273e45c7
    on_success: always
    on_failure: always
    on_start: always
    on_cancel: always
    on_error: always

stages:
  - name: deployment
    if: type != cron
  - name: retrieve
    if: type = cron

jobs:
  include:
    - stage: deployment
      script: ./deployment.sh
    - stage: retrieve
      script: ./retrieve.sh 

before_script:
  - chmod +rx deployment.sh