sudo: true
os: trusty
cache: false
language: node_js
#node_js:
  - #12
  - #node
env:
- URL=https://developer.salesforce.com/media/salesforce-cli/sfdx-linux-amd64.tar.xz
before_install:
- export BRANCH=$TRAVIS_BRANCH;
- echo $TRAVIS_BRANCH;
- echo $BRANCH;
- if ($BRANCH === 'DEV'){
      echo $SFDXAUTHURLDEV>authtravisci.txt;
  } else if ($BRANCH === 'QA'){ 
      echo $SFDXAUTHURLQA>authtravisci.txt;
  } else if ($BRANCH === 'UAT'){
      echo $SFDXAUTHURLUAT>authtravisci.txt;
  } else {
      echo $SFDXAUTHURL>authtravisci.txt;
  }
- openssl version
- export SFDX_AUTOUPDATE_DISABLE=false
- export SFDX_USE_GENERIC_UNIX_KEYCHAIN=true
- export SFDX_DOMAIN_RETRY=300
- export SFDX_DISABLE_APP_HUB=true
- export SFDX_LOG_LEVEL=DEBUG
- mkdir sfdx
- wget -qO- $URL | tar xJ -C sfdx --strip-components 1
- "./sfdx/install"
- export PATH=./sfdx/$(pwd):$PATH
- sfdx --version
- sfdx plugins --core
#- echo $SFDXAUTHURL>authtravisci.txt
- sfdx force:auth:sfdxurl:store -f authtravisci.txt -a targetEnvironment
before_script:
- export DEPLOYDIR=force-app/main/default
- export TESTLEVEL=RunLocalTests
- sfdx --version
- sfdx plugins --core
script:
- echo openssl version
- sfdx force:org:display -u targetEnvironment
- sfdx force:source:deploy --wait 10 --sourcepath $DEPLOYDIR --testlevel $TESTLEVEL -u targetEnvironment
- sfdx force:apex:test:run -u targetEnvironment --wait 10
