os: trusty
cache: false
env:
  jobs:
    - URL=https://developer.salesforce.com/media/salesforce-cli/sfdx-linux-amd64.tar.xz
#lines 7-8 can be activated in place of 11-12 and return same output  
  #global:
    #- CHANGED_FILES=`git diff --name-only master force-app/`
before_install:
- openssl version
- export SFDX_AUTOUPDATE_DISABLE=false
- export SFDX_USE_GENERIC_UNIX_KEYCHAIN=true
- export SFDX_DOMAIN_RETRY=300
- export SFDX_DISABLE_APP_HUB=true
- export SFDX_LOG_LEVEL=DEBUG
- mkdir sfdx
- wget -qO- $URL | tar xJ -C sfdx --strip-components 1
- "./sfdx/install"
- export PATH=./sfdx/$(pwd):$PATH
- sfdx --version
- sfdx plugins --core
before_script:

#make git fetch work to pull all the remote branches:

# Keep track of where Travis put us.
# We are on a detached head, and we need to be able to go back to it.
- export build_head=$(git rev-parse HEAD)
- echo $build_head;
# Fetch all the remote branches. Travis clones with `--depth`, which
# implies `--single-branch`, so we need to overwrite remote.origin.fetch to do that.
- git config --replace-all remote.origin.fetch +refs/heads/*:refs/remotes/origin/*
- git fetch
#branch recognition configuration
- export BRANCH=$TRAVIS_BRANCH;
- echo $TRAVIS_BRANCH;
- echo $BRANCH;
# create the tacking branches
- if [ "$BRANCH" == "dev" ]; then
      git checkout origin/dev;
  fi;
- if [ "$BRANCH" == "qa" ]; then
      git checkout qa;
  fi; 
- if [ "$BRANCH" == "uat" ]; then
      git checkout uat;
  fi; 
- if [ "$BRANCH" == "master" ]; then
      git checkout master;
  fi; 
# finally, go back to where we were at the beginning
- git checkout $build_head;


#incremental build configuration
- echo `git diff --name-only @{u} force-app/`;
  #- export CHANGED_FILES=`git diff --name-only @{u} force-app/`;
##get this working below
#- echo $CHANGED_FILES;
#- |
  #for CHANGED_FILE in $CHANGED_FILES do
    #echo ../$CHANGED_FILE;
  #end
#- export DIFF=$CHANGED_FILE;
#- echo $DIFF;
  #add to if statements for inc. builds
- if [ "$BRANCH" == "dev" ]; then
      echo $SFDXAUTHURLDEV>authtravisci.txt;
  fi;
- if [ "$BRANCH" == "qa" ]; then
      echo $SFDXAUTHURLQA>authtravisci.txt;
  fi; 
- if [ "$BRANCH" == "uat" ]; then
      echo $SFDXAUTHURLUAT>authtravisci.txt;
  fi; 
- if [ "$BRANCH" == "master" ]; then
      echo $SFDXAUTHURL>authtravisci.txt;
  fi; 
- sfdx force:auth:sfdxurl:store -f authtravisci.txt -a targetEnvironment
- export DEPLOYDIR=force-app/main/default
- export TESTLEVEL=RunLocalTests
- sfdx --version
- sfdx plugins --core
script:
- sfdx force:org:display -u targetEnvironment
- sfdx force:source:deploy --wait 10 --sourcepath $DEPLOYDIR --testlevel $TESTLEVEL -u targetEnvironment
- sfdx force:apex:test:run -u targetEnvironment --wait 10