cache: false
env:
  - URL=https://developer.salesforce.com/media/salesforce-cli/sfdx-linux-amd64.tar.xz
before_install:
- export SFDX_AUTOUPDATE_DISABLE=false
- export SFDX_USE_GENERIC_UNIX_KEYCHAIN=true
- export SFDX_DOMAIN_RETRY=300
- export SFDX_DISABLE_APP_HUB=true
- export SFDX_LOG_LEVEL=DEBUG
- mkdir sfdx
- wget -qO- $URL | tar xJ -C sfdx --strip-components 1
- "./sfdx/install"
- export PATH=./sfdx/$(pwd):$PATH
- sfdx --version
- sfdx plugins --core
#test mkdir locally, then migrate any changes
- sudo mkdir -p /Users/jackbarsotti/sfdx-travisci2/force-app/main/default/diff;
before_script:
- export build_head=$(git rev-parse HEAD)
- echo $build_head;
- git config --replace-all remote.origin.fetch +refs/heads/*:refs/remotes/origin/*
- git fetch

- export BRANCH=$TRAVIS_BRANCH;
- export branch=$TRAVIS_BRANCH;
- echo $TRAVIS_BRANCH;

#test to see if mkdir location matters
#- sudo mkdir -p /force-app/main/default/diff;

- >
  if [ "$BRANCH" == "dev" ]; then
    echo 'Your current branches: ';
    echo ' ';
    for branch in $(git branch -r|grep -v HEAD); do
        echo $branch;
        git checkout -qf ${branch#origin/}
    done;

  export CHANGED_FILES=`git diff --name-status master force-app/`;
  echo ' ';
  echo 'Your changed file(s): ';
  echo ' ';
  for CHANGED_FILE in $CHANGED_FILES; do
    echo ../$CHANGED_FILE;
  done;
  echo ' ';
  sudo cp --parents $(git diff --name-only master force-app/) /Users/jackbarsotti/sfdx-travisci2/force-app/main/default/diff;

  fi; 
- >
  if [ "$BRANCH" == "qa" ]; then
    echo 'Your current branches: ';
    echo ' ';
    for branch in $(git branch -r|grep -v HEAD); do
        echo $branch;
        git checkout -qf ${branch#origin/}
    done;

  export CHANGED_FILES=`git diff --name-only dev force-app/`;
  echo ' ';
  echo 'Your changed file(s): ';
  echo ' ';
  for CHANGED_FILE in $CHANGED_FILES; do
    echo ../$CHANGED_FILE;
  done;
  export DIFF=$CHANGED_FILE;

  fi; 
- >
  if [ "$BRANCH" == "uat" ]; then
    echo 'Your current branches: ';
    echo ' ';
    for branch in $(git branch -r|grep -v HEAD); do
        echo $branch;
        git checkout -qf ${branch#origin/}
    done;

  export CHANGED_FILES=`git diff --name-only qa force-app/`;
  echo ' ';
  echo 'Your changed file(s): ';
  echo ' ';
  for CHANGED_FILE in $CHANGED_FILES; do
    echo ../$CHANGED_FILE;
  done;
  export DIFF=$CHANGED_FILE;

  fi; 
- >
  if [ "$BRANCH" == "master" ]; then
    echo 'Your current branches: ';
    echo ' ';
    for branch in $(git branch -r|grep -v HEAD); do
        echo $branch;
        git checkout -qf ${branch#origin/}
    done;

  export CHANGED_FILES=`git diff --name-only dev force-app/`;
  echo ' ';
  echo 'Your changed file(s): ';
  echo ' ';
  for CHANGED_FILE in $CHANGED_FILES; do
    echo ../$CHANGED_FILE;
  done;
  export DIFF=$CHANGED_FILE;

  fi; 

- git checkout $build_head;

- if [ "$BRANCH" == "dev" ]; then
      echo $SFDXAUTHURLDEV>authtravisci.txt;
  fi;
- if [ "$BRANCH" == "qa" ]; then
      echo $SFDXAUTHURLQA>authtravisci.txt;
  fi; 
- if [ "$BRANCH" == "uat" ]; then
      echo $SFDXAUTHURLUAT>authtravisci.txt;
  fi; 
- if [ "$BRANCH" == "master" ]; then
      echo $SFDXAUTHURL>authtravisci.txt;
  fi; 
- sfdx force:auth:sfdxurl:store -f authtravisci.txt -a targetEnvironment
# for full builds: - export DEPLOYDIR=force-app/main/default
# To fix error below, update env variable DEPLOYDIR path on travis 
- export DEPLOYDIR=/Users/jackbarsotti/sfdx-travisci2/force-app/main/default/diff
- export TESTLEVEL=RunLocalTests
script:
- sfdx force:org:display -u targetEnvironment
- sfdx force:source:deploy --wait 10 --sourcepath $DEPLOYDIR --testlevel $TESTLEVEL -u targetEnvironment
#Don't need: - sfdx force:apex:test:run -u targetEnvironment --wait 10

# Store the deploy result (rewrite in Ruby, keep in same spot) could add to auth:
- rc4 = command "${toolbelt}/sfdx force:source:deploy --wait 10 --sourcepath $DEPLOYDIR --testlevel $TESTLEVEL -u targetEnvironment"
- if [ rc4 != 0 ]; then
      error 'There was an issue deploying. Check ORG deployment status page for details';
  fi;