cache: false
env:
  - URL=https://developer.salesforce.com/media/salesforce-cli/sfdx-linux-amd64.tar.xz
before_install:
- export SFDX_AUTOUPDATE_DISABLE=false
- export SFDX_USE_GENERIC_UNIX_KEYCHAIN=true
- export SFDX_DOMAIN_RETRY=300
- export SFDX_DISABLE_APP_HUB=true
- export SFDX_LOG_LEVEL=DEBUG
- mkdir sfdx
- wget -qO- $URL | tar xJ -C sfdx --strip-components 1
- "./sfdx/install"
- export PATH=./sfdx/$(pwd):$PATH
- sfdx --version
- sfdx plugins --core
- sudo mkdir -p /Users/jackbarsotti/sfdx-travisci2/force-app/main/default/diff/variants;
before_script:
- export build_head=$(git rev-parse HEAD)
- echo $build_head
- git config --replace-all remote.origin.fetch +refs/heads/*:refs/remotes/origin/*
- git fetch

- export BRANCH=$TRAVIS_BRANCH
- export branch=$TRAVIS_BRANCH
- echo $TRAVIS_BRANCH
#Remember to add these throughout the build. update ` ` code, update --parents
- export userPath=/Users/jackbarsotti/sfdx-travisci2/force-app/main/default;
- export diffPath=/diff/force-app/main/default;

- >
  if [ "$BRANCH" == "dev" ]; then
    echo 'Your current branches: '
    echo
    for branch in $(git branch -r|grep -v HEAD); do
        echo $branch
        git checkout -qf ${branch#origin/}
    done;
    echo
    git checkout dev

    export CHANGED_FILES=`git diff --name-only master force-app/`
    sudo cp --parents $(git diff --name-only master force-app/) /Users/jackbarsotti/sfdx-travisci2/force-app/main/default/diff;

    echo
    echo 'Your changed files: '
    echo
    for FILE in $CHANGED_FILES; do
      echo ../$FILE
    done;
    echo

  fi; 

- >
  if [ "$BRANCH" == "qa" ]; then
    echo 'Your current branches: '
    echo
    for branch in $(git branch -r|grep -v HEAD); do
        echo $branch
        git checkout -qf ${branch#origin/}
    done;
    echo
    git checkout qa

    export CHANGED_FILES=`git diff --name-only dev force-app/`
    sudo cp --parents $(git diff --name-only dev force-app/) /Users/jackbarsotti/sfdx-travisci2/force-app/main/default/diff;

    echo
    echo 'Your changed files: '
    echo
    for FILE in $CHANGED_FILES; do
      echo ../$FILE
    done;
    echo

  fi; 

- >
  if [ "$BRANCH" == "uat" ]; then
    echo 'Your current branches: '
    echo
    for branch in $(git branch -r|grep -v HEAD); do
        echo $branch
        git checkout -qf ${branch#origin/}
    done;
    echo
    git checkout uat

    export CHANGED_FILES=`git diff --name-only qa force-app/`
    sudo cp --parents $(git diff --name-only qa force-app/) /Users/jackbarsotti/sfdx-travisci2/force-app/main/default/diff;

    echo
    echo 'Your changed files: '
    echo
    for FILE in $CHANGED_FILES; do
      echo ../$FILE
    done;
    echo

  fi; 

- >
  if [ "$BRANCH" == "master" ]; then
    echo 'Your current branches: '
    echo
    for branch in $(git branch -r|grep -v HEAD); do
        echo $branch
        git checkout -qf ${branch#origin/}
    done;
    echo
    git checkout master

    export CHANGED_FILES=`git diff --name-only dev force-app/`
    sudo cp --parents $(git diff --name-only dev force-app/) /Users/jackbarsotti/sfdx-travisci2/force-app/main/default/diff;

    echo
    echo 'Your changed files: '
    echo
    for FILE in $CHANGED_FILES; do
      echo ../$FILE
    done;
    echo

  fi; 

#in progress
#NOTE: new classs naming convention used: "Test"
#- export classVariations=$(find force-app/main/default/classes -name "*Test.cls" -o -name "*Test.class-meta.xml");
- for FILE in $CHANGED_FILES; do
    echo ' ';
    echo "Found changed file:`echo ' '$FILE`";
    if [[ $FILE == *.cls-meta.xml ]]; then
      export FILE2=${FILE%.cls-meta.xml};
      export classes=$(find force-app/main/default/classes -samefile "$FILE2.cls");
      sudo cp --parents "$(find force-app/main/default/classes -samefile "$FILE2.cls")"* /Users/jackbarsotti/sfdx-travisci2/force-app/main/default/diff;
      
      export classVariations=$(find force-app/main/default/classes -samefile "$FILE2Test.cls" -o -samefile "$FILE2Test.class-meta.xml");
      sudo cp "$classVariations"* $userPath/diff/variants;
      echo 'Copying class meta file to diff folder for deployment...';
      echo 'Class files that will be deployed:';
      ls $userPath$diffPath/classes;
      ls $userPath/diff/variants;

    elif [[ $FILE == *.cls ]]; then
      export classMetas=$(find force-app/main/default/classes -samefile "$FILE-meta.xml");
      sudo cp --parents "$(find force-app/main/default/classes -samefile "$FILE-meta.xml")"* /Users/jackbarsotti/sfdx-travisci2/force-app/main/default/diff;            
      
      export classVariations=$(find force-app/main/default/classes -samefile "$FILETest.cls" -o -samefile "$FILETest.class-meta.xml");
      sudo cp "$classVariations"* $userPath/diff/variants;
      echo 'Copying class file to diff folder for deployment...';
      echo 'Class files that will be deployed:';      
      ls $userPath$diffPath/classes;
      ls $userPath/diff/variants;

    elif [[ $FILE == *.trigger-meta.xml ]]; then
      export FILE3=${FILE%.trigger-meta.xml};
      export triggers=$(find force-app/main/default/triggers -samefile "$FILE3.trigger");
      sudo cp --parents "$(find force-app/main/default/triggers -samefile "$FILE3.trigger")"* /Users/jackbarsotti/sfdx-travisci2/force-app/main/default/diff;
      echo 'Copying trigger meta file to diff folder for deployment...';
      echo 'Trigger files that will be deployed:';
      ls $userPath$diffPath/triggers;

    elif [[ $FILE == *.trigger ]]; then
      export triggerMetas=$(find force-app/main/default/triggers -samefile "$FILE-meta.xml");
      sudo cp --parents "$(find force-app/main/default/triggers -samefile "$FILE-meta.xml")"* /Users/jackbarsotti/sfdx-travisci2/force-app/main/default/diff;
      echo 'Copying trigger file to diff folder for deployment...';
      echo 'Trigger files that will be deployed:';
      ls $userPath$diffPath/triggers;
    fi;
  done;

#create variable and csv file with *test.cls files:
#      export classVariations="$(find force-app/main/default/classes -name "*test.cls" -o -name "*test.class-meta.xml")";
#      echo $classVariations>deployClasses.csv;
#      sudo cp deployClasses.csv /Users/jackbarsotti/sfdx-travisci2/force-app/main/default/diff;
- git checkout $build_head;

- if [ "$BRANCH" == "dev" ]; then
      echo $SFDXAUTHURLDEV>authtravisci.txt;
      
  fi;
- if [ "$BRANCH" == "qa" ]; then
      echo $SFDXAUTHURLQA>authtravisci.txt;
      export TESTLEVEL='RunSpecifiedTests -r $classVariations';
  fi; 
- if [ "$BRANCH" == "uat" ]; then
      echo $SFDXAUTHURLUAT>authtravisci.txt;
      export TESTLEVEL=RunLocalTests;
  fi; 
- if [ "$BRANCH" == "master" ]; then
      echo $SFDXAUTHURL>authtravisci.txt;
      export TESTLEVEL=RunLocalTests;
  fi; 
- sfdx force:auth:sfdxurl:store -f authtravisci.txt -a targetEnvironment
# for full builds: - export DEPLOYDIR=force-app/main/default
- export DEPLOYDIR=/Users/jackbarsotti/sfdx-travisci2/force-app/main/default/diff
- export deployErrorMsg='There was an issue deploying. Check ORG deployment status page for details'
script:
- sfdx force:org:display -u targetEnvironment
#how do we call an env variable after -r?
- sfdx force:source:deploy -w 10 -p $DEPLOYDIR -l RunSpecifiedTests -r newNewClassTest,frankensteinClassTest -u targetEnvironment
after_failure:
- if [ TRAVIS_TEST_RESULT != 0 ]; then
      echo $deployErrorMsg
  fi;