os: trusty
cache: false
env:
  - URL=https://developer.salesforce.com/media/salesforce-cli/sfdx-linux-amd64.tar.xz
before_install:
- openssl version
- export SFDX_AUTOUPDATE_DISABLE=false
- export SFDX_USE_GENERIC_UNIX_KEYCHAIN=true
- export SFDX_DOMAIN_RETRY=300
- export SFDX_DISABLE_APP_HUB=true
- export SFDX_LOG_LEVEL=DEBUG
- mkdir sfdx
- wget -qO- $URL | tar xJ -C sfdx --strip-components 1
- "./sfdx/install"
- export PATH=./sfdx/$(pwd):$PATH
- sfdx --version
- sfdx plugins --core
#testing mkdir -p
- sudo mkdir -p /force-app/main/default/diff;
before_script:
- export build_head=$(git rev-parse HEAD)
- echo $build_head;
- git config --replace-all remote.origin.fetch +refs/heads/*:refs/remotes/origin/*
- git fetch

- export BRANCH=$TRAVIS_BRANCH;
- echo $TRAVIS_BRANCH;
- echo $BRANCH;
- export branch=$TRAVIS_BRANCH;
- echo $branch;
#new
- sudo mkdir -p ../force-app/main/default/diff;
#- export deploydir=`git diff --name-only HEAD...$DIFF`;
#- echo $deploydir;
  # ^force-app/main/default/diff;

- >
  if [ "$BRANCH" == "dev" ]; then
    echo 'Your current branches: ';
    echo ' ';
    for branch in $(git branch -r|grep -v HEAD); do
        echo $branch;
        git checkout ${branch#origin/};
    done;

  export CHANGED_FILES=`git diff --name-only master force-app/`;
  echo ' ';
  echo 'Your changed file(s): ';
  echo ' ';
  for CHANGED_FILE in $CHANGED_FILES; do
    echo ../$CHANGED_FILE;
  done;
  export DIFF=$CHANGED_FILE;

  fi;
- >
  if [ "$BRANCH" == "qa" ]; then
    echo 'Your current branches: ';
    echo ' ';
    for branch in $(git branch -r|grep -v HEAD); do
        echo $branch;
        git checkout -qf ${branch#origin/}
    done;

  export CHANGED_FILES=`git diff --name-only dev force-app/`;
  echo ' ';
  echo 'Your changed file(s): ';
  echo ' ';
  for CHANGED_FILE in $CHANGED_FILES; do
    echo ../$CHANGED_FILE;
  done;
  export DIFF=$CHANGED_FILE;

  fi; 
- >
  if [ "$BRANCH" == "uat" ]; then
    echo 'Your current branches: ';
    echo ' ';
    for branch in $(git branch -r|grep -v HEAD); do
        echo $branch;
        git checkout -qf ${branch#origin/}
    done;

  export CHANGED_FILES=`git diff --name-only qa force-app/`;
  echo ' ';
  echo 'Your changed file(s): ';
  echo ' ';
  for CHANGED_FILE in $CHANGED_FILES; do
    echo ../$CHANGED_FILE;
  done;
  export DIFF=$CHANGED_FILE;

  fi; 
- >
  if [ "$BRANCH" == "master" ]; then
    echo 'Your current branches: ';
    echo ' ';
    for branch in $(git branch -r|grep -v HEAD); do
        echo $branch;
        git checkout -qf ${branch#origin/}
    done;

  export CHANGED_FILES=`git diff --name-only dev force-app/`;
  echo ' ';
  echo 'Your changed file(s): ';
  echo ' ';
  for CHANGED_FILE in $CHANGED_FILES; do
    echo ../$CHANGED_FILE;
  
  done;
  sudo cp $(git diff --name-only dev force-app/) /force-app/main/default/diff;

  fi; 
# line 109 could try: sudo cp "echo $CHANGED_FILE"

#be aware of this:
- git checkout $build_head;

- if [ "$BRANCH" == "dev" ]; then
      echo $SFDXAUTHURLDEV>authtravisci.txt;
  fi;
- if [ "$BRANCH" == "qa" ]; then
      echo $SFDXAUTHURLQA>authtravisci.txt;
  fi; 
- if [ "$BRANCH" == "uat" ]; then
      echo $SFDXAUTHURLUAT>authtravisci.txt;
  fi; 
- if [ "$BRANCH" == "master" ]; then
      echo $SFDXAUTHURL>authtravisci.txt;
  fi; 
- sfdx force:auth:sfdxurl:store -f authtravisci.txt -a targetEnvironment
# for full builds: - export DEPLOYDIR=force-app/main/default
# export below returns error bc /diff, doesn't match travis env variable DEPLOYDIR path
- export DEPLOYDIR=force-app/main/default/diff
- export TESTLEVEL=RunLocalTests
- sfdx --version
- sfdx plugins --core
script:
- sfdx force:org:display -u targetEnvironment
- sfdx force:source:deploy --wait 10 --sourcepath $DEPLOYDIR --testlevel $TESTLEVEL -u targetEnvironment
#- sfdx force:apex:test:run -u targetEnvironment --wait 10

# Store the deploy result (rewrite in Ruby, keep in same spot):
#- rc4 = command "${toolbelt}/sfdx force:source:deploy --wait 10 --sourcepath $DEPLOYDIR --testlevel $TEST_LEVEL -u targetEnvironment"
#    if (rc4 != 0) {
#        error 'There was an issue deploying. Check ORG deployment status page for details'
#    }